export const LOGIN_STATE = 'login-state'
export const USER_STATE = 'user-state'
export const SERVER_STATE = 'server-state'
export const TOKEN_STATE = 'token-state'
export const LOG_STATE = 'log-state'
export const ATTRIBUTE_STATE = 'attribute-state'
